# Conversion
markdown:   kramdown
highlighter:    rouge

# File Locations
destination:    ./_site
layouts_dir:    _layouts

# File Reading
encoding:   "utf-8"
exclude:    ["Gemfile", "Gemfile.lock", "node_modules", "vendor/bundle/", "vendor/cache/", "vendor/gems/", "vendor/ruby/", "README.md"]

# Other
name:   Vingenuity